<?php $_config_vars = array (
  'sections' => 
  array (
  ),
  'vars' => 
  array (
    'clock_discription' => 'Uhrzeit',
    'clock_unit' => 'Uhr',
    'date_discription' => 'Datum',
    'date_unit' => '',
    'time_discription' => 'Zeitraum',
    'time_unit' => 'h',
    'type_discription' => 'Type',
    'type_unit' => '',
    'ID_discription' => 'ID',
    'page_discription' => 'Seite',
    'x_discription' => 'X',
    'y_discription' => 'Y',
    'name_discription' => 'Name',
    'objectid_discription' => 'Object ID',
    'info_discription' => 'Daemon Job',
    'active_discription' => 'Status',
    'options_discription' => 'Optionen',
    'active' => 'aktiv',
    'inactive' => 'inaktiv',
    'error' => 'fehler',
    'activate' => 'aktivieren',
    'deactivate' => 'deaktivieren',
    'edit' => 'bearbeiten',
    'delete' => 'löschen',
    'add_a_new_object' => 'Ein neues Objekt hinzufügen...',
    'add_a_new_page' => 'Eine neue Seite hinzufügen...',
    'name' => 'Name',
    'x' => 'X-Pos',
    'y' => 'Y-Pos',
    'template' => 'Template',
    'daemonjob' => 'Daemon Job',
    'controlpanel' => 'Control Panel',
    'station_protocol' => 'Station Protokoll',
    'page' => 'Seite',
    'savebutton' => 'Konfiguration Speichern',
    'page_object_add_clone' => 'Clonen eines vorhandenen Objektes',
    'page_object_add_diffpage' => 'Ein vorhandenes Objekt einer weiteren Seite zuordnen',
    'page_object_add_new' => 'Hinzufügen eines neuen Objektes',
    'page_object_add_newspecial' => 'Hinzufügen eines neuen Special Objektes',
    'objectid' => 'ObjektID',
  ),
); ?>